swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http

paths:
  /user/accountInfos:
    get:
      summary: "Get all transactions for the current month"
      description: "Retrieves a list of all transactions for the current month."
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Transaction"
        401:
          description: "Unauthorized - Missing or invalid API key"
      security:
        - apiKey: []

    post:
      summary: "Add additional information to a transaction"
      description: "Adds additional information to a transaction."
      parameters:
        - name: "body"
          in: "body"
          description: "Additional information for the new transaction"
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      responses:
        201:
          description: "Successful operation - Created"
        401:
          description: "Unauthorized - Missing or invalid API key"

  /transactions/{transactionId}:
    get:
      summary: "Get details of a transaction"
      description: "Retrieves additional details of a transaction by specifying its ID."
      parameters:
        - name: "transactionId"
          in: "path"
          description: "Transaction ID"
          required: true
          type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Transaction"
        401:
          description: "Unauthorized - Missing or invalid API key"
        404:
          description: "Transaction not found"
      security:
        - apiKey: []

    put:
      summary: "Modify details of a transaction"
      description: "Modifies the additional details of a transaction by specifying its ID."
      parameters:
        - name: "transactionId"
          in: "path"
          description: "Transaction ID"
          required: true
          type: "string"
        - name: "body"
          in: "body"
          description: "New transaction details"
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      responses:
        200:
          description: "Successful operation"
        401:
          description: "Unauthorized - Missing or invalid API key"
        404:
          description: "Transaction not found"
      security:
        - apiKey: []

    delete:
      summary: "Delete a transaction"
      description: "Deletes a transaction by specifying its ID."
      parameters:
        - name: "transactionId"
          in: "path"
          description: "Transaction ID"
          required: true
          type: "string"
      responses:
        204:
          description: "Successful operation - No content"
        401:
          description: "Unauthorized - Missing or invalid API key"
        404:
          description: "Transaction not found"
      security:
        - apiKey: []

definitions:
  Transaction:
    type: "object"
    properties:
      id:
        type: "string"
      date:
        type: "string"
        format: "date"
      amount:
        type: "number"
      description:
        type: "string"
